### ISSUE TITLE
Is there a way to use Git hooks to add the Typescript compiled file after it is built?

### ISSUE THREAD

**Issue by TimeDropsSB** [Sylphony/git-hook-test#1]
@vutran Is there any way using husky (or another tool) to allow a Git `precommit` hook to build a Typescript file but then also add the built Javascript file to the commit as well?  I don't think it is possible since it was never `git add` initially.

**Comment by vutran** [comment]
It's best to not include compiled assets into your repository. If you're publishing a new package on `npm`, just have your `build` script run on `prepublish`.

Example: https://github.com/vutran/twas/blob/master/package.json#L25

**Comment by TimeDropsSB** [comment]
Yarn has issues with `prepublish` unfortunately.  Guess I will settle for using npm to publish instead then.

That's fantastic though.  That helps keep the dist files out of the repo but still make it available for npm.

Thanks for the help!
